const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const generatePDF = (reportData, outputPath) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true });
            const writeStream = fs.createWriteStream(outputPath);

            doc.pipe(writeStream);

            // --- Header Section ---
            doc.fontSize(20).text("Classroom Observation Report (COB)", { align: 'center', underline: true });
            doc.moveDown();

            const header = reportData.cob_report.header;
            doc.fontSize(12).font('Helvetica-Bold');
            doc.text(`Facilitator: ${header.facilitator || 'N/A'}`);
            doc.text(`Topic: ${header.topic_blm || 'N/A'}`);
            doc.text(`Duration: ${header.duration || 'N/A'}`);
            doc.text(`Date of Report: ${new Date().toLocaleDateString()}`);
            doc.moveDown();

            // --- Score Summary ---
            const scores = reportData.cob_report.scores;
            doc.fontSize(14).text("Summary", { underline: true });
            doc.fontSize(12).font('Helvetica');
            doc.text(`Overall Percentage: ${scores.overall_percentage || 'N/A'}`);
            if (scores.summary) {
                doc.text(`Performance Summary: ${scores.summary}`);
            }
            doc.moveDown();



            // --- Parameters Table ---
            doc.fontSize(14).font('Helvetica-Bold').text("Detailed Parameter Analysis", { underline: true });
            doc.moveDown(0.5);

            const params = reportData.cob_report.parameters || [];

            // Simple Iterate and Print (Table-like structure)
            params.forEach((param, index) => {
                // Check for page break space
                if (doc.y > 700) doc.addPage();

                doc.fontSize(11).font('Helvetica-Bold').fillColor('#2d3748');
                doc.text(`${index + 1}. ${param.name} (${param.category})`);

                doc.font('Helvetica').fillColor('black');
                doc.text(`Score: ${param.score} / ${param.out_of}    Weight: ${param.weight || 'N/A'}`);

                doc.fontSize(10).font('Helvetica-Oblique').fillColor('#4a5568');
                doc.text(`Comment: ${param.comment}`, { indent: 10 });

                doc.moveDown(0.8);
                doc.strokeColor('#e2e8f0').lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
                doc.moveDown(0.8);
                doc.fillColor('black'); // Reset color
            });

            // --- Highlights & Observations ---
            if (doc.y > 650) doc.addPage();
            doc.moveDown();

            if (reportData.cob_report.highlights && reportData.cob_report.highlights.length > 0) {
                doc.fontSize(14).font('Helvetica-Bold').text("Highlights");
                doc.fontSize(11).font('Helvetica');
                reportData.cob_report.highlights.forEach(h => doc.text(`• ${h}`));
                doc.moveDown();
            }

            if (reportData.cob_report.other_observations && reportData.cob_report.other_observations.length > 0) {
                doc.fontSize(14).font('Helvetica-Bold').text("Other Observations");
                doc.fontSize(11).font('Helvetica');
                reportData.cob_report.other_observations.forEach(o => doc.text(`• ${o}`));
            }

            // --- What Happened Section (End of Report) ---
            doc.moveDown();
            if (reportData.cob_report.what_happened && reportData.cob_report.what_happened.length > 0) {
                doc.fontSize(14).font('Helvetica-Bold').text("What happened during the session:", { underline: true });
                doc.fontSize(11).font('Helvetica');
                doc.moveDown(0.5);
                reportData.cob_report.what_happened.forEach(h => {
                    doc.text(`• ${h}`, { indent: 15 });
                });
                doc.moveDown();
            }

            // Footer
            const range = doc.bufferedPageRange();
            for (let i = 0; i < range.count; i++) {
                doc.switchToPage(i);
                doc.fontSize(9).text(
                    `Page ${i + 1} of ${range.count} - Generated by AI Auditor`,
                    50,
                    doc.page.height - 50,
                    { align: "center", color: "gray" }
                );
            }

            doc.end();

            writeStream.on('finish', () => {
                resolve(outputPath);
            });

            writeStream.on('error', (err) => {
                reject(err);
            });

        } catch (error) {
            reject(error);
        }
    });
};

module.exports = { generatePDF };
