/**
 * lessonPlanReportService.js
 * 
 * Acts as the PDF presentation layer for Lesson Plans specifically.
 * Takes the raw JSON report generated by Gemini (Yes/No format),
 * and maps it dynamically to a structured HTML table matching the user's Excel Rubric.
 */
const puppeteer = require('puppeteer');
const fs = require('fs');

/**
 * Generates a PDF report matching the Lesson Plan Excel Rubric format.
 */
const generateLessonPlanReportFromHtml = async (data, outputPath) => {
    try {
        const report = data.lesson_plan_report || {};
        const headerData = report.header || {};
        const params = report.parameters || [];
        const overallStatus = report.overall_status || "UNKNOWN";

        // Group parameters by Heading
        const grouped = {};
        const headingOrder = [];
        params.forEach(p => {
            const heading = p.heading || 'General';
            if (!grouped[heading]) {
                grouped[heading] = [];
                headingOrder.push(heading);
            }
            grouped[heading].push(p);
        });

        // Determine Status Color
        let statusColor = "#333";
        if (overallStatus === "ACCEPTED") statusColor = "green";
        if (overallStatus === "REWORK REQUIRED") statusColor = "blue";
        if (overallStatus === "RESUBMISSION REQUIRED") statusColor = "red";

        // Build Table Rows
        let tableRowsHtml = "";
        let totalEarned = 0;
        let totalOutOf = 0;

        headingOrder.forEach(heading => {
            const rowCount = grouped[heading].length;
            grouped[heading].forEach((p, index) => {
                if (p.weighted_score !== undefined && !isNaN(p.weighted_score)) totalEarned += Number(p.weighted_score);
                if (p.out_of !== undefined && !isNaN(p.out_of)) totalOutOf += Number(p.out_of);
                let scoreColor = p.raw_score < 2 ? 'red' : 'green';
                let consequenceColor = '';
                let printedConsequence = p.if_no_consequence || '-';

                if (p.raw_score === 2) {
                    consequenceColor = 'green';
                    printedConsequence = 'ACCEPTED';
                } else {
                    if (printedConsequence.toUpperCase().includes("RESUBMISSION")) consequenceColor = 'red';
                    else if (printedConsequence.toUpperCase().includes("REWORK")) consequenceColor = 'blue';
                    else consequenceColor = 'red'; // Default to red if consequence triggered
                }

                tableRowsHtml += `<tr>`;
                
                // Only print the heading on the first row of the group, and make it span multiple rows
                if (index === 0) {
                    tableRowsHtml += `<td rowspan="${rowCount}" style="font-weight: bold; padding: 8px; border: 1px solid #000; vertical-align: top;">${heading}</td>`;
                }
                
                tableRowsHtml += `
                    <td style="text-align: center; padding: 8px; border: 1px solid #000;">${p.parameter_no || '-'}</td>
                    <td style="padding: 8px; border: 1px solid #000;">${p.parameter}</td>
                    <td style="text-align: center; font-weight: bold; color: ${scoreColor}; padding: 8px; border: 1px solid #000;">${p.yes_no || '-'}</td>
                    <td style="text-align: center; font-weight: bold; color: ${scoreColor}; padding: 8px; border: 1px solid #000;">${p.raw_score !== undefined ? p.raw_score : '-'}</td>
                    <td style="text-align: center; padding: 8px; border: 1px solid #000;">${p.ooi || 1}</td>
                    <td style="text-align: center; font-weight: bold; color: ${scoreColor}; padding: 8px; border: 1px solid #000;">${p.weighted_score !== undefined ? p.weighted_score : '-'}</td>
                    <td style="text-align: center; padding: 8px; border: 1px solid #000;">${p.out_of || '-'}</td>
                    <td style="text-align: center; font-weight: bold; color: ${consequenceColor}; padding: 8px; border: 1px solid #000; font-size: 10px;">${printedConsequence}</td>
                    <td style="padding: 8px; border: 1px solid #000; font-size: 11px; color: #555;">${p.remark || ''}</td>
                </tr>`;
            });
        });

        tableRowsHtml += `
            <tr style="background-color: #d1d5db; font-weight: bold;">
                <td colspan="6" style="text-align: right; padding: 8px; border: 1px solid #000;">TOTAL SCORE:</td>
                <td style="text-align: center; padding: 8px; border: 1px solid #000;">${totalEarned}</td>
                <td style="text-align: center; padding: 8px; border: 1px solid #000;">${totalOutOf}</td>
                <td colspan="2" style="border: 1px solid #000; background-color: #e5e7eb;"></td>
            </tr>
        `;

        const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                body {
                    font-family: Arial, sans-serif;
                    margin: 20px;
                    font-size: 12px;
                    color: #333;
                }
                table {
                    width: 100%;
                    border-collapse: collapse;
                    margin-top: 20px;
                }
                th {
                    background-color: #f2f2f2;
                    border: 1px solid #000;
                    padding: 8px;
                    text-align: center;
                    font-weight: bold;
                }
                .header-section {
                    margin-bottom: 20px;
                }
                .header-table {
                    width: 100%;
                    border: none;
                }
                .header-table td {
                    padding: 4px;
                }
                .status-box {
                    font-size: 16px;
                    font-weight: bold;
                    margin-top: 20px;
                    padding: 10px;
                    border: 2px solid ${statusColor};
                    color: ${statusColor};
                    text-align: center;
                    background-color: #f9f9f9;
                }
            </style>
        </head>
        <body>
            <div class="header-section">
                <h2 style="text-align: center; margin-bottom: 20px;">Lesson Plan Evaluation Report</h2>
                <table class="header-table">
                    <tr>
                        <td><strong>Teacher:</strong> ${headerData.facilitator || 'N/A'}</td>
                        <td><strong>School:</strong> ${headerData.school || 'N/A'}</td>
                    </tr>
                    <tr>
                        <td><strong>Grade/Section:</strong> ${headerData.grade || 'N/A'} - ${headerData.section || 'N/A'}</td>
                        <td><strong>Subject:</strong> ${headerData.subject || 'N/A'}</td>
                    </tr>
                    <tr>
                        <td><strong>Date:</strong> ${headerData.date || 'N/A'}</td>
                        <td><strong>Rubric:</strong> ${headerData.rubric_name || 'Standard'}</td>
                    </tr>
                </table>
            </div>

            <div class="status-box">
                OVERALL STATUS: ${overallStatus} 
                <span style="font-size: 14px; color: #555; display: block; margin-top: 5px;">Score: ${report.scores?.overall_percentage || '0%'}</span>
            </div>

            <table>
                <thead>
                    <tr>
                        <th style="width: 12%;">Heading</th>
                        <th style="width: 3%;">No.</th>
                        <th style="width: 25%;">Parameters</th>
                        <th style="width: 5%;">Yes/No</th>
                        <th style="width: 5%;">Score (0-2)</th>
                        <th style="width: 5%;">OOI</th>
                        <th style="width: 5%;">Earned Score</th>
                        <th style="width: 5%;">Out Of</th>
                        <th style="width: 10%;">If No</th>
                        <th style="width: 25%;">AI Remark</th>
                    </tr>
                </thead>
                <tbody>
                    ${tableRowsHtml}
                </tbody>
            </table>
            
            <div style="margin-top: 30px; font-size: 10px; color: #777;">
                <strong>Evaluation Logic:</strong>
                <ul>
                    <li>For an LP to be ACCEPTED, all parameters should have a 'Yes' score.</li>
                    <li>RESUBMISSION REQUIRED takes precedence over REWORK REQUIRED. If an LP has both RESUBMISSIONS and REWORKS, then this LP will be considered to be RESUBMISSION category.</li>
                    <li>If an LP has only REWORK REQUIRED and no RESUBMISSION REQUIRED, only then will it be in the REWORK REQUIRED category.</li>
                </ul>
            </div>
        </body>
        </html>
        `;

        const browser = await puppeteer.launch({
            headless: 'new',
            args: ['--no-sandbox', '--disable-setuid-sandbox']
        });
        const page = await browser.newPage();
        
        await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
        
        await page.pdf({
            path: outputPath,
            format: 'A4',
            printBackground: true,
            margin: { top: '20px', right: '20px', bottom: '20px', left: '20px' }
        });
        
        await browser.close();
        return true;
    } catch (error) {
        console.error("Error generating Lesson Plan PDF from HTML:", error);
        throw error;
    }
};

module.exports = {
    generateLessonPlanReportFromHtml
};
